name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make

    - name: Create build directory
      run: mkdir build && cd build

    - name: Configure with CMake
      working-directory: build
      run: cmake ..

    - name: Build project
      working-directory: build
      run: cmake --build .

    - name: Run tests (if any)
      working-directory: build
      run: ctest || true  # 如果没有测试，可以跳过这一步或注释掉
