name: Build and Release Windows Executable

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install MinGW-w64 and CMake
        run: |
          choco install mingw -y
          choco install cmake -y

      - name: Add MinGW to PATH
        run: |
          $env:Path += ";C:\ProgramData\chocolatey\bin"
          $env:Path += ";C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"

      - name: Verify GCC and CMake installation
        run: |
          gcc --version
          cmake --version

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"

      - name: Build project
        run: |
          cd build
          mingw32-make

      - name: Package executable
        run: |
          cd build
          mkdir -p ../release
          Copy-Item DLL_Injection_XiaoaiAgent.exe ../release/

      - name: Check if release tag exists
        id: check_release
        run: |
          try {
            Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.inputs.release_tag }}" -Method HEAD -StatusCodeVariable statusCode
            if ($statusCode -eq 200) {
              Write-Output "##[set-output name=exists]true"
            }
          } catch {
            Write-Output "##[set-output name=exists]false"
          }

      - name: Create Release
        if: steps.check_release.outputs.exists == 'false'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          release_name: Release ${{ github.event.inputs.release_tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use PAT instead of default GITHUB_TOKEN

      - name: Update Release
        if: steps.check_release.outputs.exists == 'true'
        id: update_release
        uses: octokit/request-action@v5.x
        with:
          route: PATCH /repos/${{ github.repository }}/releases/tags/${{ github.event.inputs.release_tag }}
          data: |
            {
              "draft": false,
              "prerelease": false
            }
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Upload Release Asset
        needs: [create_release, update_release]
        if: always()
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url || needs.update_release.data.upload_url }}
          asset_path: ./release/DLL_Injection_XiaoaiAgent.exe
          asset_name: DLL_Injection_XiaoaiAgent.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use PAT instead of default GITHUB_TOKEN



