name: Build and Release Windows Executable

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install MinGW-w64 and CMake
        run: |
          choco install mingw -y
          choco install cmake -y

      - name: Add MinGW to PATH
        run: |
          echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

      - name: Verify GCC and CMake installation
        run: |
          gcc --version
          cmake --version

      - name: Configure CMake for static linking
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" -DCMAKE_EXE_LINKER_FLAGS="-static"

      - name: Build project statically
        run: |
          cd build
          mingw32-make

      - name: Package executable
        run: |
          cd build
          mkdir -p ../release
          cp DLL_Injection_XiaoaiAgent.exe ../release/

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name:  DLL_Injection_XiaoaiAgent.exe
          path:  build/DLL_Injection_XiaoaiAgent.exe




