name: CMake with MinGW

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MSYS2 and MinGW
      run: |
        choco install msys2 -y --no-progress
        refreshenv
        pacman -Syu --needed --noconfirm base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake

    - name: Set up environment variables
      run: |
        echo "MINGW_PATH=C:\tools\msys64\mingw64\bin" >> $GITHUB_ENV
        echo "PATH=$MINGW_PATH;$PATH" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B ${GITHUB_WORKSPACE}/build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: mingw32-make -C ${GITHUB_WORKSPACE}/build

    - name: Test
      working-directory: ${GITHUB_WORKSPACE}/build
      run: ctest -C ${{ env.BUILD_TYPE }}



